### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by 2bbb** [2bbb/ofxPubSubOsc#2]
memorandum

**Comment by 2bbb** [comment]
[ ] add const for argument of ofxPublishOsc (now removed for first aid)
[ ] change priority of ofxOscPublisher::update to after app update

**Comment by 2bbb** [comment]
- [ ] change default value of argument of `ofxPublishOsc`/`bool whenValueIsChanged` from *false* to *true*
- [ ] design the conditional publish system
- [ ] design the system that kicks callbacks about publish

**Comment by 2bbb** [comment]
- [ ] update README: write detail of arguments of `ofxPublishOsc` / i.e. specify `whenValueIsChanged`
- [ ] update README: write detail of `ofxOscSubscriber` and `ofxOscPublisher`

**Comment by 2bbb** [comment]
- [ ] add publish ofBuffer

**Comment by 2bbb** [comment]
* [ ] correct publishing array
* [ ] correct publishing const getter like `T(U::*)() const`

**Comment by 2bbb** [comment]
* [ ] refactor and update lambdas
* [ ] map to multimap
  * [ ] update erase algorithm
  * [ ] update return value void to identifer
